# Generated by Django 6.0.7 on 2026-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_product_cost_price_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('returned', 'Returned')], default='sale', max_length=20),
        ),
    ]
