# Generated by Django 6.0.7 on 2026-08-20 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_userdeletionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_report_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_report_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_deduct_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='daily_report_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='daily_report_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='date_format',
            field=models.CharField(choices=[('d/m/Y', 'DD/MM/YYYY'), ('m/d/Y', 'MM/DD/YYYY'), ('Y-m-d', 'YYYY-MM-DD')], default='d/m/Y', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('pos', 'POS')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='low_stock_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='out_of_stock_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Thank you for your patronage.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_show_cashier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_show_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_show_payment_method',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_show_sku',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_format',
            field=models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='12', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
