# Generated by Django 6.0.7 on 2026-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_systemsettings_ai_report_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='last_ai_report_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_daily_report_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
