# Generated by Django 6.0.7 on 2026-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='stock_deducted',
            field=models.BooleanField(default=True),
        ),
    ]
