# Generated by Django 6.0.7 on 2026-08-31 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_saleitem_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
