# Generated by Django 6.0.7 on 2026-08-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_activitylog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='updated_at',
        ),
    ]
